### ISSUE TITLE
[Bug] Checkpoint downloaded outside of LM failing to match for CivitAI

### ISSUE THREAD

**Issue by Brennok** [willmiao/ComfyUI-Lora-Manager#238]
### **LoRA Manager Version**
- Version: `v0.8.17-bugfix

I downloaded a few models last night and didn't have LM running. I updated today and it is failing to match them to the CivitAI listing. I didn't rename them so not sure what is causing the match to fail on fetch. 

https://civitai.com/models/1527265?modelVersionId=1891804
https://civitai.com/models/1663724/erucation
https://civitai.com/models/1665837?modelVersionId=1909615
https://civitai.com/models/1677673/lustrijous

**Comment by willmiao** [comment]
Fixed! This was caused by AI unexpectedly changing a default value during recent code refactoring, which led to the issue when generating skeleton metadata for manually added models. As a result, LoRA Manager skipped those models during the fetch process. I don’t use this workflow often myself, so I missed it in testing—sorry about that!

For the models you've already scanned that failed to fetch metadata, you can right-click and choose "Refresh CivitAI Metadata" to update them.

Much appreciate the feedback!

**Comment by Brennok** [comment]
Update still doesn't seem to be fetching anything. Nothing in the command window either. 

I deleted the JSON created for each of the 4. Quick refresh didn't prompt LM to make new JSONs, I did a full rebuild which generated new JSONs, but it still can't seem to match these 4. 

I checked the sha256 which matches CivitAI so not sure if you have any ideas. 

[tiberiumIllustrious_v30.metadata.json](https://github.com/user-attachments/files/20826244/tiberiumIllustrious_v30.metadata.json)
[lustrijous_no1.metadata.json](https://github.com/user-attachments/files/20826243/lustrijous_no1.metadata.json)
[glosscoreIllustrious_v20.metadata.json](https://github.com/user-attachments/files/20826245/glosscoreIllustrious_v20.metadata.json)
[erucation_v10.metadata.json](https://github.com/user-attachments/files/20826242/erucation_v10.metadata.json)

**Comment by willmiao** [comment]
Hmm, that’s odd. I tested using the same checkpoint—the first one you listed—manually moved it to the model folder, clicked Refresh and then Fetch, and the metadata was pulled successfully. The metadata files you provided also seem with no problem. 

Just to confirm, does right-click → Refresh CivitAI data not work for you either?

![Image](https://github.com/user-attachments/assets/98478a09-f006-4e1d-a957-b9ff24ece889)

**Comment by Brennok** [comment]
Thanks, that worked. I always forget about the right click option.
