### ISSUE TITLE
[BUG] - After "Searching" viewer no longer "searches subfolders" or "displays" sub folders, even LoRA's in sub folders.

### ISSUE THREAD

**Issue by SencneS** [willmiao/ComfyUI-Lora-Manager#415]
### **LoRA Manager Version**
- Version: v0.9.2

### **Issue Description**
After trying to search, it appears to not revert back to "Including subfolders". Best to show examples here.

There are LoRA's in the styles folder, AND in sub folders in the Styles directory.

<img width="1367" height="510" alt="Image" src="https://github.com/user-attachments/assets/7935051e-0460-4dbe-8867-2de6b84c3a7a" />
This is the Windows Explorer view

<img width="620" height="375" alt="Image" src="https://github.com/user-attachments/assets/60f3ad91-616b-497d-b829-913880406271" />

If I search for something, lets use the Sunglasses
It finds it.

<img width="1379" height="495" alt="Image" src="https://github.com/user-attachments/assets/4ceb7db5-882f-4fce-aa90-90b66e7bc37a" />

But here is something interesting  - The folder the "Styles" folder resides in is the "Flux.1D" folder. If I go to that folder. It reports this.

<img width="1396" height="649" alt="Image" src="https://github.com/user-attachments/assets/aa8274f6-bc8c-431b-a4ae-9818607ec611" />

There is indeed zero lora's in the main folder. It only has sub folders filled with LoRA's and Folders.
But if I search from the Flux.1D folder (Or any primary model folder that doesn't contain any LoRAs). I get this...

<img width="1357" height="635" alt="Image" src="https://github.com/user-attachments/assets/160dbd87-5904-4175-9f12-25729aa54f68" />

There is no message, it's like it's deliberately not searching anything.
If I press "F5" to refresh the page, All of a sudden the LoRA's show up again.

<img width="1439" height="679" alt="Image" src="https://github.com/user-attachments/assets/7c4bc83c-7985-4d0c-a9df-4dc0495ccc85" />

It doesn't matter which folder I go to, even if I press the little "x" in the search bar, it never recovers the default view of including subfolders.

<img width="1393" height="627" alt="Image" src="https://github.com/user-attachments/assets/7fbe2bdb-73dc-46f0-8bc8-74cb57453bde" />

So after I search I kinda have to press "F5" to 'reset' the interface.

Something is not right here.

**Comment by AppleJack0012** [comment]
Having the same issue. Searching for anything on the latest updade of this node does not display anything like the previous versions.

**Comment by willmiao** [comment]
A fix has been pushed. Please update and try it out.

**Comment by AppleJack0012** [comment]
The update did not fix it. Below is a screenshot.

<img width="1118" height="360" alt="Image" src="https://github.com/user-attachments/assets/9af23e76-6b3f-444b-b50a-60bdbac5f15a" />

**Comment by willmiao** [comment]
> The update did not fix it. Below is a screenshot.

You’ll need to update to the latest nightly version to get the fix (it’s not available in the stable version you’re currently on). To update, go to ComfyUI Manager → search for LoRA Manager → Switch Version → select ‘nightly.’ If you’re using the portable version, you can just run `update.bat` instead.

**Comment by AppleJack0012** [comment]
> > The update did not fix it. Below is a screenshot.
> 
> You’ll need to update to the latest nightly version to get the fix (it’s not available in the stable version you’re currently on). To update, go to ComfyUI Manager → search for LoRA Manager → Switch Version → select ‘nightly.’ If you’re using the portable version, you can just run `update.bat` instead.

Got it, doing it right now. Will let you know as soon as Comfy is back up and I test it!

**Comment by AppleJack0012** [comment]
It is working! Thank you for your hard work! I'm guessing you can either close it out, or let the OG close it out. Again thank you so very much! ♥♥♥♥♥♥♥

**Comment by SencneS** [comment]
Works perfectly from what I can see - Thank you Willmiao!
