### ISSUE TITLE
NSFW filter doesn't work automatically for LoRas we already had previous to this feature

### ISSUE THREAD

**Issue by diodiogod** [willmiao/ComfyUI-Lora-Manager#53]
NSFW filter doesn't work automatically for LoRas we already had previous to this feature. If I add new loras to the lora folder and fetch the data, it will blur NSFW content correctly. But for all the loras on my collection it does not work, only if I edit them manually... Is there a way to rebuild this specific filter for past loras?

If I open the lora details, the image inside them are blurred, but not the cover. 

If you need any logs, I can get try to get them, but I don't see any errors really.

**Comment by willmiao** [comment]
Hi,

The reason for this is that when an image is fetched directly by the manager (either by fetching or downloading a LoRA), the manager knows which image it is and can retrieve the NSFW level from its metadata. However, pre-existing images might have been added before LoRA Manager was installed or manually replaced by the user. Because of this, I can’t assume they are the same as any of the showcase images.

Maybe I need to use Perceptual Hash or a similar method to compare the existing preview with the first showcase image.

**Comment by diodiogod** [comment]
> Hi,
> 
> The reason for this is that when an image is fetched directly by the manager (either by fetching or downloading a LoRA), the manager knows which image it is and can retrieve the NSFW level from its metadata. However, pre-existing images might have been added before LoRA Manager was installed or manually replaced by the user. Because of this, I can’t assume they are the same as any of the showcase images.
> 
> Maybe I need to use Perceptual Hash or a similar method to compare the existing preview with the first showcase image.

Maybe a button on the settings to redownload covers from LoRas (that still exists on Civitai) could be enough?
But maybe your solution could be better, IDK.
In any case thanks for looking into this!

**Comment by willmiao** [comment]
Hi, I just revisited this issue and realized I overcomplicated it. Since manually replacing preview images is far less common than simply using the first example image as the preview, I’ve updated the code to default the preview image’s NSFW level to match the first example image (if missing).

If users do manually replace the preview image, they can still adjust the NSFW level afterward as needed.

**Comment by diodiogod** [comment]
@willmiao I opened this issue because older loras (imported from older version of lora manager before it had the NSFW filter) don't work properly with the NSFW filter. This is still an issue for me on the current version. Is there any way to refresh the download of previews and metadata of older loras so they can be blurred if they are NSFW?

**Comment by willmiao** [comment]
This commit is intended to address the issue you mentioned. It sets the `preview_nsfw_level` based on the `nsfwLevel` of the first example image in the model metadata retrieved from Civitai—this value has always been present and is key to determining NSFW status on the frontend.

I'm not sure if the issue on your end is that none of the NSFW previews are being blurred, or if only certain models are not behaving as expected. If it's just a few, it's possible that the `nsfwLevel` wasn't correctly set in the metadata.

Currently, the web UI doesn't support batch operations to **_force_** refresh previews and metadata. As a workaround, you can open the model folder in your file explorer, sort by date, and delete the older preview files and corresponding .metadata.json files. Then, restart LoRA Manager and click the 'Fetch' button on the page to re-download them.

**Comment by diodiogod** [comment]
> This commit is intended to address the issue you mentioned. It sets the `preview_nsfw_level` based on the `nsfwLevel` of the first example image in the model metadata retrieved from Civitai—this value has always been present and is key to determining NSFW status on the frontend.
> 
> I'm not sure if the issue on your end is that none of the NSFW previews are being blurred, or if only certain models are not behaving as expected. If it's just a few, it's possible that the `nsfwLevel` wasn't correctly set in the metadata.
> 
> Currently, the web UI doesn't support batch operations to **_force_** refresh previews and metadata. As a workaround, you can open the model folder in your file explorer, sort by date, and delete the older preview files and corresponding .metadata.json files. Then, restart LoRA Manager and click the 'Fetch' button on the page to re-download them.

After looking into some of my older loras metadata jsons, they have the "nsfwLevel" on the images on the json set to something like "8", but there is no "preview_nsfw_level" field on the problematic ones, which leads to it showing up unblurred. They DO have a "nsfw" tag like this:

    "model": {
      "name": "NSFWLORANAME",
      "type": "LORA",
      "nsfw": true,
      "poi": false
    },

But they are unblurred.

I have a really large collection and going on each of them manually even just to delete the json would require a lot of time. Of course, an approach could be just to delete all jsons, but that could lead to more problems as a lot of loras are constantly deleted from Civitai. So I'm not sure. Of course this is doable. But it makes me wonder if there is no way to fix these jsons that don't have a "preview_nsfw_level" field.

**Comment by willmiao** [comment]
> After looking into some of my older loras metadata jsons, they have the "nsfwLevel" on the images on the json set to something like "8", but there is no "preview_nsfw_level" field on the problematic ones, which leads to it showing up unblurred. 

The absence of the preview_nsfw_level field in the JSON file is expected—LoRA Manager reads the nsfwLevel from the first image and sets preview_nsfw_level in memory, which is then passed to the frontend to decide whether to blur the preview. I’ve avoided writing it back to the JSON for now, since updating large collections can be time-consuming.

It’s working correctly on my end, so this behavior is a bit unexpected. Just to confirm—are you on the latest nightly version, and is the “Blur NSFW Content” setting enabled?

**Comment by diodiogod** [comment]
> > After looking into some of my older loras metadata jsons, they have the "nsfwLevel" on the images on the json set to something like "8", but there is no "preview_nsfw_level" field on the problematic ones, which leads to it showing up unblurred.
> 
> The absence of the `preview_nsfw_level` field in the JSON file is expected—LoRA Manager reads the `nsfwLevel` from the first image and sets `preview_nsfw_level` in memory, which is then passed to the frontend to decide whether to blur the preview. I’ve avoided writing it back to the JSON for now, since updating large collections can be time-consuming.
> 
> It’s working correctly on my end, so this behavior is a bit unexpected. Just to confirm—are you on the latest nightly version, and is the “Blur NSFW Content” setting enabled?

Oh my, I'm so sorry! It is working! I was not on Nightly. I've just switched and now it's working. 
I DID try just early today to update to nightly, but the node was not loading when starting comfyUI, that is why a switched back to the latest version instead of nightly. But I guess you might have corrected it by now, because it is working perfectly. Sorry again, and thank you for this!!
