### ISSUE TITLE
Rate Limits never respected or retried...

### ISSUE THREAD

**Issue by scruffynerf** [willmiao/ComfyUI-Lora-Manager#647]
### **LoRA Manager Version**
- Version: `v0.9.9`

### **Environment Information**
- **Operating System**: Ubuntu 22.04

### **Issue Description**
Pile of "errors":
Rate limit encountered for GET https://civarchive.com/api/sha256/8ce396d04b5eeb9603097223151511534e9f600cb3e8e4ea89e7af4f8f1518af; retry_after=5.0
Rate limited by civarchive_api; retry after approximately 5s
[make_request] Using system-level proxy (trust_env) if configured.
Rate limit encountered for GET https://civarchive.com/api/sha256/3c8180a87cf5007142efc7912fcb7cd8cb45eeaf37df7c156e452c0e49cac204; retry_after=5.0
Rate limited by civarchive_api; retry after approximately 5s

Counts down IF there are a lot of lookups, but never actually retries...

### **Expected Behavior**
In the civarchive patch I submitted, I properly handled the rate limit, including actual pausing before retry.
I realize you removed that in favor of your code, but your code doesn't actually work.  Any rate limit essentially just fails.

**Comment by willmiao** [comment]
Hi, thanks for catching this — and sorry I didn’t test it thoroughly earlier.
I’ve just pushed a fix, and it now retries properly after hitting the rate limit. Please update and give it another try!

**Comment by scruffynerf** [comment]
Better... but still not quite right I think... not sure all of the spots calling the API respect this rate limiting... (Downloading for one, if you hit the model urls too fast, it'll trip the site limit and fail)
